### ISSUE TITLE
Season setup game scraping script does not store timezone for games

### ISSUE THREAD

**Issue by ameske** [ameske/nfl-pickem#11]
The python script that scrapes the NFL's website and extracts the games for a season does not store the timestamps with timezone information. This causes headaches when trying to calculate whether or not a game has already started and cannot be picked. Currently, this is worked around in the app, but it would be ideal for future years to store the timezone correctly

**Comment by TheRumpledOne** [comment]
Hello:  Do you know how to contact the people at PHP PICKEM?  There seems to be a problem when I load the system.  There are bugs in the index.php.

**Comment by ameske** [comment]
Fixed in database-cleanup branch
